name: Release with commit

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v2.8.1
        with:
            regexp: "Release ((\\d+([.]\\d+)*) - ((\\s|\\S)*))"
            regexp_options: "us"
            release_name: "version $2"
            tag_name: "v$2"
            body: "$4"
            draft: false
            prerelease: false
        env:
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' # This token is provided by Actions, you do not need to create your own token
